services:
  - type: web
    name: hue-hunt-v2
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    disk:
      name: hue-hunt-data
      mountPath: /tmp
      sizeGB: 1